### ISSUE TITLE
Что значит каждая из этих переменных?

### ISSUE THREAD

**Issue by coursar** [Roman-code37/Sportmaster#9]
https://github.com/Roman-code37/Sportmaster/blob/fdf207cd23ad0450d3572fe8323be4205819a5e8/src/Main.java#L4-L5

**Comment by Roman-code37** [comment]
amount for purchases - сумма покупок;
purchases - покупки.

**Comment by coursar** [comment]
Ничего не понял )) чем сумма покупок отличается от покупок )) у вас же наверняка в покупках не количество (штуки)?

**Comment by Roman-code37** [comment]
да, покупки в рублях, не в штуках) сумма покупок - это сумма старых покупок, а покупки это текущие) но я уже их переименовал, теперь всё понятно
